# time_shader_compiles.py
# This file is part of I, Voyager
# https://ivoyager.dev
# *****************************************************************************
# Copyright 2019-2026 Charlie Whitfield
# I, Voyager is a registered trademark of Charlie Whitfield in the US
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *****************************************************************************
"""Time each Core shader's from-scratch compile and link, one shader per process.

The GL Compatibility renderer compiles a shader program at first draw, on the main
thread, synchronously -- so a shader's compile cost is a frame time, and the plugin's
SHADER_COMPILE_COST.md is the record of what that costs and what drives it. This
script is how that record is remeasured. It reports, per shader, the frame in which
a fresh material first draws (the four scene-shader variants at the default
specialization mask plus the one actually requested), and the frame after the light
is hidden (one further specialization, which the renderer compiles in full).

It does not measure the hosting project. It generates a throwaway Godot project in
a temp directory holding a copy of the Core plugin's shaders, the project's
[shader_globals] block, and shader_compile_timer.gd as its main scene; then runs one
Godot process per shader against it. Every part of that arrangement answers a way
the measurement goes wrong:

  - One shader per process. In a sequence the AMD driver leaked work from earlier
    compiles into later first-draw frames -- a 1.07 s shader read 9.7 s after three
    heavy ones, and a figure this document once carried was that artefact.
  - A fresh project each run, plus a uniquely named uniform appended to the shader
    being timed. Godot hashes the GLSL it generates and the GL driver caches
    program binaries under that, so a rerun of unchanged source answers from cache
    in milliseconds. A comment cannot bust it: the parser drops comments before the
    hash. Only novel source misses both caches, which is what a real edit is.
  - The whole shaders directory is copied, not just the file under test, and the
    shader is loaded from a path rather than built at runtime: a runtime Shader has
    no resource path, so the relative #includes the shipped files use would not
    resolve.
  - [shader_globals] is copied from the hosting project. Core shaders declare
    global uniforms (iv_exposure, iv_display_encode, ...) that the Core editor
    plugin writes into project.godot; without them nothing compiles.
  - A trivial shader is drawn first and discarded. Its first draw also pays the
    probe quad's own.

Because the copy is made fresh on every run, there is nothing here to keep in sync
with the plugin: what it measures is always the shaders as they are on disk now.

Usage (from the project directory, the one holding project.godot):

    python addons/tools/time_shader_compiles.py                  # every spatial shader
    python addons/tools/time_shader_compiles.py surface atmosphere_limb
    python addons/tools/time_shader_compiles.py --renderer forward_plus

Requires the sibling submodule addons/ivoyager_core (the shaders it measures) and a
Godot executable; by default the newest Godot_v*_console.exe beside the project.
Compatibility is the default renderer because it is the one that hurts, and the one
the web export uses. Godot's --print-fps is enough to find a stall in a normal
session, but not to attribute one; that is what this is for.
"""

import argparse
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import uuid

import _project

SHADERS_SUBDIR = pathlib.Path("addons") / "ivoyager_core" / "shaders"
TIMER_SCRIPT_NAME = "shader_compile_timer.gd"
COPIED_SUFFIXES = (".gdshader", ".gdshaderinc")
RESULT_RE = re.compile(r"^SHADER_TIMER (\S+) first_ms=(\d+) spec_ms=(\d+)", re.M)
ERROR_RE = re.compile(r"^SHADER_TIMER_ERROR (.*)$", re.M)

PROJECT_GODOT_TEMPLATE = """\
; Generated by addons/tools/time_shader_compiles.py. Throwaway; edit nothing here.
config_version=5

[application]

config/name="shader_compile_timer"
run/main_scene="res://main.tscn"

[debug]

settings/stdout/verbose_stdout=false

{shader_globals}
"""

MAIN_TSCN = """\
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://shader_compile_timer.gd" id="1"]

[node name="Main" type="Node3D"]
script = ExtResource("1")
"""


def find_godot(project_dir):
    """Return the newest Godot_v*_console.exe beside the project, or exit saying so."""
    candidates = sorted(project_dir.parent.glob("Godot_v*_console.exe"))
    candidates += sorted(project_dir.parent.glob("godot*.console.exe"))
    if not candidates:
        sys.exit(f"No Godot console executable found in '{project_dir.parent}'.\n"
                 f"Pass one with --godot.")
    return max(candidates, key=lambda path: path.stat().st_mtime)


def read_shader_globals(project_dir):
    """Return the hosting project.godot's [shader_globals] section, verbatim."""
    text = (project_dir / "project.godot").read_text(encoding="utf-8")
    start = text.find("[shader_globals]")
    if start == -1:
        return ""
    end = text.find("\n[", start + 1)
    return text[start:] if end == -1 else text[start:end]


def list_shaders(shaders_dir):
    """Return the names of every .gdshader in the Core plugin, sorted."""
    return sorted(path.stem for path in shaders_dir.glob("*.gdshader"))


def build_harness(harness_dir, project_dir, shaders_dir):
    """Write the throwaway project: main scene, timer script, a copy of the shaders."""
    (harness_dir / "project.godot").write_text(
            PROJECT_GODOT_TEMPLATE.format(shader_globals=read_shader_globals(project_dir)),
            encoding="utf-8")
    (harness_dir / "main.tscn").write_text(MAIN_TSCN, encoding="utf-8")
    shutil.copy2(pathlib.Path(__file__).resolve().parent / TIMER_SCRIPT_NAME,
                 harness_dir / "shader_compile_timer.gd")
    harness_shaders = harness_dir / "shaders"
    harness_shaders.mkdir()
    for path in shaders_dir.iterdir():
        if path.suffix in COPIED_SUFFIXES:
            shutil.copy2(path, harness_shaders / path.name)
    return harness_shaders


def bust_cache(shader_path):
    """Append a uniquely named uniform, so neither shader cache can answer.

    An unused uniform changes the GLSL Godot generates and so the key both it and
    the GL driver cache under, without changing what the shader draws."""
    with shader_path.open("a", encoding="utf-8") as file:
        file.write(f"\nuniform float _timer_bust_{uuid.uuid4().hex[:12]};\n")


def time_shader(godot, harness_dir, harness_shaders, name, renderer, timeout):
    """Run one Godot process for one shader. Returns (first_ms, spec_ms) or None."""
    shader_path = harness_shaders / f"{name}.gdshader"
    if not shader_path.is_file():
        return None, f"no such shader '{name}'"
    bust_cache(shader_path)
    command = [str(godot), "--path", str(harness_dir), "--rendering-method", renderer,
               "--windowed", "--resolution", "400x300", "--position", "0,0",
               "--", f"--shader={name}"]
    try:
        completed = subprocess.run(command, capture_output=True, text=True,
                                   timeout=timeout)
    except subprocess.TimeoutExpired:
        return None, f"timed out after {timeout} s"
    output = (completed.stdout or "") + (completed.stderr or "")
    error = ERROR_RE.search(output)
    if error:
        return None, error.group(1).strip()
    match = RESULT_RE.search(output)
    if not match:
        return None, "no result line (run with --verbose to see Godot's output)"
    return (int(match.group(2)), int(match.group(3))), None


def main():
    parser = argparse.ArgumentParser(
            description="Time each Core shader's from-scratch compile, one per process.",
            epilog="Reports the first-draw frame and the frame that follows hiding the "
                   "light, which is one further specialization. See "
                   "addons/ivoyager_core/SHADER_COMPILE_COST.md.")
    parser.add_argument("shaders", nargs="*",
                        help="shader names without extension (default: all of them)")
    parser.add_argument("--renderer", default="gl_compatibility",
                        choices=["gl_compatibility", "forward_plus", "mobile"],
                        help="renderer to measure (default: gl_compatibility)")
    parser.add_argument("--godot", type=pathlib.Path,
                        help="Godot executable (default: newest Godot_v*_console.exe "
                             "beside the project)")
    parser.add_argument("--timeout", type=int, default=900,
                        help="seconds one shader may take before it is abandoned "
                             "(default: 900)")
    parser.add_argument("--keep", action="store_true",
                        help="keep the generated project and print its path")
    parser.add_argument("--list", action="store_true",
                        help="list the shader names and exit")
    parser.add_argument("--verbose", action="store_true",
                        help="echo each Godot command before running it")
    args = parser.parse_args()

    project_dir = _project.project_dir()
    shaders_dir = project_dir / SHADERS_SUBDIR
    if not shaders_dir.is_dir():
        sys.exit(f"No shaders at '{shaders_dir}'. This script needs the sibling "
                 f"submodule addons/ivoyager_core.")
    names = args.shaders or list_shaders(shaders_dir)
    if args.list:
        print("\n".join(list_shaders(shaders_dir)))
        return
    godot = args.godot or find_godot(project_dir)
    if not pathlib.Path(godot).is_file():
        sys.exit(f"No Godot executable at '{godot}'.")

    harness_dir = pathlib.Path(tempfile.mkdtemp(prefix="iv_shader_timer_"))
    try:
        harness_shaders = build_harness(harness_dir, project_dir, shaders_dir)
        print(f"{args.renderer}, {len(names)} shader(s), one process each. "
              f"Each is a cold compile; this is slow by construction.\n")
        width = max(len(name) for name in names)
        print(f"{'shader'.ljust(width)}   first draw   +1 spec")
        failures = []
        for name in names:
            if args.verbose:
                print(f"  [{name}]", flush=True)
            result, error = time_shader(godot, harness_dir, harness_shaders, name,
                                        args.renderer, args.timeout)
            if error:
                print(f"{name.ljust(width)}   -- {error}")
                failures.append(name)
                continue
            first_ms, spec_ms = result
            print(f"{name.ljust(width)}   {first_ms / 1000.0:7.2f} s   "
                  f"{spec_ms / 1000.0:6.2f} s", flush=True)
        if failures:
            print(f"\n{len(failures)} shader(s) not measured: {', '.join(failures)}")
    finally:
        if args.keep:
            print(f"\nGenerated project kept at '{harness_dir}'.")
        else:
            shutil.rmtree(harness_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
